// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DataDirectory() {
  return window['go']['main']['App']['DataDirectory']();
}

export function OperatingSystem() {
  return window['go']['main']['App']['OperatingSystem']();
}
