// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DataDirectory():Promise<string>;

export function GetDevicesListStatus():Promise<main.DeviceOtaMeta>;

export function GetFilteredListOfDevices(arg1:main.OtaDevicesFilter):Promise<Array<main.DeviceOta>>;

export function OperatingSystem():Promise<string>;

export function RetrieveBlobsWithPrefix(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<main.BlobInformation>>;

export function UpdateOtaDeviceList(arg1:string):Promise<string>;
