// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AzureGetOtaDevices(arg1:string,arg2:main.OtaDevicesFilter):Promise<Array<{[key: string]: string}>>;

export function DataDirectory():Promise<string>;

export function OperatingSystem():Promise<string>;
