// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DataDirectory():Promise<string>;

export function GetDevicesListStatus():Promise<main.DeviceOtaMeta>;

export function OperatingSystem():Promise<string>;

export function UpdateOtaDeviceList(arg1:string):Promise<string>;
