// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DataDirectory() {
  return window['go']['main']['App']['DataDirectory']();
}

export function GetDevicesListStatus() {
  return window['go']['main']['App']['GetDevicesListStatus']();
}

export function GetFilteredListOfDevices(arg1) {
  return window['go']['main']['App']['GetFilteredListOfDevices'](arg1);
}

export function OperatingSystem() {
  return window['go']['main']['App']['OperatingSystem']();
}

export function RetrieveBlobsWithPrefix(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RetrieveBlobsWithPrefix'](arg1, arg2, arg3, arg4);
}

export function UpdateOtaDeviceList(arg1) {
  return window['go']['main']['App']['UpdateOtaDeviceList'](arg1);
}
